"""Host udev rules — the one root-gated setup step of podstage.

The rootless runtime container needs two udev rules on the host:

  * ``99-podstage-virtual-inputs.rules`` (static, shipped in ``host/``) — pins
    the streaming input devices to seat9 with MODE=0600 so they never reach
    the desktop seat.
  * ``71-podstage-input-owner.rules`` (generated here, per-user) — chowns the
    same devices plus ``/dev/uinput`` to the user. The container runs with
    ``--userns=keep-id``, so its processes carry this host uid; group access
    does not map through the rootless user namespace, owner-uid does. This is
    the complete DAC story — no groups involved.

``podstage setup`` (CLI) prints the sudo install commands; the GUI's Setup
page runs :func:`install_shell` through pkexec. Installing them once is the
only root interaction podstage ever needs — day-to-day start/stop is a plain
rootless ``podman run``.
"""

from __future__ import annotations

import getpass
import shlex
from pathlib import Path

from .. import config

REPO_ROOT = Path(__file__).resolve().parents[3]
STAGING_DIR = config.DATA_DIR / "setup"

STATIC_SRC = REPO_ROOT / "host/99-podstage-virtual-inputs.rules"
STATIC_DEST = Path("/etc/udev/rules.d/99-podstage-virtual-inputs.rules")
OWNER_DEST = Path("/etc/udev/rules.d/71-podstage-input-owner.rules")


def owner_rule_text(user: str | None = None) -> str:
    user = user or getpass.getuser()
    return f"""\
# podstage — per-user input DAC for the ROOTLESS runtime container.
# Generated by podstage for user {user}; regenerate via `podstage setup` if
# the user changes. Seat pinning + MODE live in the static rule
# (99-podstage-virtual-inputs.rules) — this file only grants access.
#
# The container runs with --userns=keep-id, so its processes carry this host
# uid. Group access does not map through the rootless user namespace —
# owner-uid does.
SUBSYSTEMS=="input", ATTRS{{name}}=="Sunshine*", OWNER="{user}"
SUBSYSTEMS=="input", ATTRS{{name}}=="*passthrough*", OWNER="{user}"
SUBSYSTEMS=="input", ATTRS{{id/vendor}}=="28de", OWNER="{user}"
# Sunshine (in the container, as this uid) creates its virtual devices on the
# REAL /dev/uinput — own it so the rootless container can open it.
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", OWNER="{user}"
"""


def stage() -> dict[str, Path]:
    """Write the generated owner rule to the staging dir; returns name → path
    for both rules (the static one straight from the repo)."""
    STAGING_DIR.mkdir(parents=True, exist_ok=True)
    owner = STAGING_DIR / OWNER_DEST.name
    owner.write_text(owner_rule_text())
    return {"static": STATIC_SRC, "owner": owner}


def _install_steps(staged: dict[str, Path]) -> list[str]:
    static, owner = shlex.quote(str(staged["static"])), shlex.quote(str(staged["owner"]))
    return [
        f"install -m 644 {static} {shlex.quote(str(STATIC_DEST))}",
        f"install -m 644 {owner} {shlex.quote(str(OWNER_DEST))}",
        "udevadm control --reload",
        # Re-apply OWNER to the already-existing /dev/uinput node right away;
        # the streaming devices are created fresh per stream and need no trigger.
        "udevadm trigger --sysname-match=uinput",
    ]


def install_shell(staged: dict[str, Path]) -> str:
    """The root-side install as ONE shell line — used by the GUI via pkexec
    (single auth dialog)."""
    return " && ".join(_install_steps(staged))


def install_commands(staged: dict[str, Path]) -> list[str]:
    return [f"sudo {step}" for step in _install_steps(staged)]
